### ISSUE TITLE
Install folders

### ISSUE THREAD

**Issue by djsmith** [dhilgarth/chocolatey-packages#1]
Hi,

Thanks for creating this chocolatey package, but I'm having problems using it.

When I tried running it I got several errors. My git install (ver 1.9.5.20150320 installed previously via chocolatey) doesn't have a \usr\bin\ folder nor a \etc\profile.d\ folder (I just have an \etc\ folder), so the installer can't copy the files to those folders.

I manually created a \usr\bin\ folder and an \etc\profile.d\ folder and the installer worked, but I couldn't use git-flow from the bash prompt; it errors with _git: 'flow' is not a git command. See 'git --help'._

Maybe your environment is different because you are using msys/mingw, but I think the $gitBin variable should be `$gitBin = "$gitDir"` or maybe test if the \usr folder doesn't exist if that is needed for dev work. Similarly with the git-flow-completion.sh file, perhaps that should be copied to the  \etc\ folder instead of \etc\profile.d.

Or perhaps the call to `& "$exeInstallGitFlow"` should use $gitDir instead of $gitBin?

Also, running the install more than once, maybe by using the `--force` option or during an upgrade, might fail because the `Get-ChildItem ... | Remove-Item ...` command will try to delete the files in the \gitflow\ folder cloned from a previous install, and then the call to git clone will fail because there is already a \gitflow\ folder with a repo in it.

Thanks
Dan

**Comment by dhilgarth** [comment]
Your git version is old and deprecated. Please see https://github.com/msysgit/msysgit/releases. The structure of the installation folder changed with the 2.x release. Please try updating git.
